### ISSUE TITLE
Suggestion: Show what changed by forking original, then deleting this copy

### ISSUE THREAD

**Issue by poikilos** [apanagio/directory-listing#1]
Hello,
If you go to <https://github.com/XnSger/EvoDire> then press "Fork", you can edit index.php in apanagio/EvoDire that and replace the code with yours. Then people including the original author can see what improvements you made, and you can delete apanagio/directory-listing repo to avoid confusion.

If you do that, you can even submit a pull request at XnSger/EvoDire so the original author can incorporate your improvements (in that case people often prefer you create a branch before pressing commit, so your changes can be stored in a branch named someting like apanagio-audio-support).

**Comment by poikilos** [comment]
Also, the project isn't named "Audio support for Evoluted Directory Listing Script" so instead of changing the name of the program in the README maybe instead add a change such as:
```
Audio support for Evoluted Directory Listing Script
==================================

## Changes
(2017-03-06)
(apanagio)
* add audio support
```

**Comment by apanagio** [comment]
Just did what you proposed, here is the fork:
https://github.com/apanagio/EvoDire

Thanks for the suggestions.
